var express = require("express");
var router = express.Router();

router.get("/", function(req, res, next) {
    res.send([
		{ name:'India',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/India.jpg',
		},
		{name:'Albania',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Albania.jpg',
		},
		{name:'Algeria',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Algeria.jpg',	
		},
		{name:'Andorra',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Andorra.jpg',	
		},
        {name:'Angola',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Angola.jpg'	,
		},
        {name:'Argentina',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Argentina.jpg',	
		},
        {name:'Armenia',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Armenia.jpg',	
		},
        {name:'Australia',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Australia.jpg',	
		},
        {name:'Austria',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Austria.jpg',	
		},
        {name:'Azerbaijan',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Azerbaijan.jpg',	
		},
        {name:'Bermuda',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Bermuda.jpg',	
		},
        {name:"Bhutan",
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Bhutan.jpg',	
		},
        {name:'Bolivia',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Bolivia.jpg',	
		},
        {name:'Brazil',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Brazil.jpg',	
		},
        {name:'Cayman Iskands',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Cayman_Islands.jpg',	
		},
        {name:'China',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/China.jpg',	
		},
        {name:'Colombia',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Colombia.jpg',	
		},
        {name:'England',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/England.jpg',	
		},
        {name:'Afghanistan',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Afghanistan.jpg',	
		},
        {name:'Greece',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Greece.jpg',	
		},
        {name:'Greenland',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Greenland.jpg',	
		},
        {name:'Iceland',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Iceland.jpg',	
		},
        {name:'Iran',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Iran.jpg',	
		},
        {name:'Italy',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Italy.jpg',	
		},
        {name:'Japan',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Japan.jpg',	
		},
        {name:'jordan',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Jordan.jpg',	
		},
        {name:'Kenya',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/Kenya.jpg',	
		},
        {name:'New Zealand',
			img:'https://www.sciencekids.co.nz/images/pictures/flags96/New_Zealand.jpg',	
		},


	]);
    
});

module.exports = router;